### ISSUE TITLE
Param Mutations 

### ISSUE THREAD

**Issue by PhilCK** [intel/opencl-intercept-layer#103]
## Observed Behavior

Not a huge problem, mutations occur in some of the parameters presumably for hashing and general ease. In our negative testing `clBuildProgram` tests (and others) would fail because `const char *options = nullptr` would silently get transformed into `""` (partly due to the changes you made for me in stopping null strings getting access, a few months ago)`, thus by the time it got to the impl the params would be different.

Is this desired? We test bad params alot, I know the CTS doesn't really touch this.

## Desired Behavior

The mutations in things like count in `clCreateProgramWithSource` going from `n` to 1 are fine in our testing, as they are both valid, but from invalid to valid is less clear to us if its desirable. From code inspection this looks like it will impact some of the caching.

**Comment by bashbaug** [comment]
This is interesting.  I'm not sure how to "solve" this.  We may need to look at different cases individually.

As a general rule, without any controls set, I wouldn't expect to see any parameter mutations.  If you're seeing a mutation in this case, regardless whether it's going from valid -> valid or invalid -> valid, please let me know.

When controls are set, though, there will certainly be mutations or other side effects in some cases, some of which may be desired and intuitive and some that may neither be desired nor intuitive.  We can certainly try to minimize these side effects, but I don't think we'll be able to eliminate them completely.

In the case where you're seeing the program options go from `nullptr` to `""` are any controls set?

Thanks!

**Comment by bashbaug** [comment]
Hi @PhilCK, do you have any update regarding this issue?  Thanks!

**Comment by PhilCK** [comment]
So sorry for the delay!! I'm not actually working at this company anymore so can't say what there priorities are anymore.

**Comment by bashbaug** [comment]
No problem, thanks for the update!  I think I'm just going to close this issue, since I'm not aware of any param mutations occurring by default, without setting any controls.

For anyone reading through old issues, my expectation is that parameters will only be modified when controls are set, so if a param mutation is occurring by default, please file an issue.  Thanks!
