### ISSUE TITLE
VS 2019 has no 32bit build

### ISSUE THREAD

**Issue by jgu222** [intel/opencl-intercept-layer#198]
## Observed Behavior
On Windows 10, 64 bit,  only has 64 bit build

## Desired Behavior
Need to have 32bit build as well.

## Steps to Reproduce
 cd \<root-clintercept\>
 mkdir _bin64
 cmake -G "Visual Studio 16 2019" ..
 cmake --build . --config RelWithDebInfo --target install

 This will give 64 bit build.  Note that the following has cmake error:
 cmake -G "Visual Studio 16 2019 win32" ..

**Comment by bashbaug** [comment]
Hello!

I think you need to use the the `-A` option to do this.  See:

https://cmake.org/cmake/help/git-stage/generator/Visual%20Studio%2016%202019.html

**Comment by jgu222** [comment]
Thanks.
