### ISSUE TITLE
aubcapture

### ISSUE THREAD

**Issue by jgu222** [intel/opencl-intercept-layer#199]
## Observed Behavior
No aub file found.

## Desired Behavior

aub file is expected when AubCapture is set to 1.

## Steps to Reproduce
set AubCapture to 1
run apps

* Any Intercept Layer for OpenCL Applications controls you are setting.
* The application you ran.  For large or proprietary applications, it will likely be easier to address your issue if you include a simpler reproducer.
* The OpenCL implementation and device you tested on.
* Your operating system, and any other relevant system information.

Some of this information may automatically be included if you attach your Intercept Layer for OpenCL Applications log, particularly if you set [CLInfoLogging](https://github.com/intel/opencl-intercept-layer/blob/master/docs/controls.md#clinfologging-bool).)

**Comment by bashbaug** [comment]
Can you please review the instructions documented here?

https://github.com/intel/opencl-intercept-layer/blob/master/docs/aubcapture.md

**Comment by jgu222** [comment]
I set them.  CL intercept log shows the file name,  but the file does not exist.  Only thing works for me is to set
   SetCommandStreamReceiver = 3
without using cl intercept.

*** some of log ****
Control LogToFile is set to non-default value: true
Control BuildLogging is set to non-default value: true
Control CallLogging is set to non-default value: true
Control CallLoggingEnqueueCounter is set to non-default value: true
Control AubCapture is set to non-default value: true
Control AubCaptureIndividualEnqueues is set to non-default value: true
Control AubCaptureMaxEnqueue is set to non-default value: 10

AubCapture started... maybe.  Filename is: C:/Intel/CLIntercept_Dump/openclbasemark_executable.exe/AubCapture_Enqueue_00000003_kernel_bitonicSort_G_32768_L_NULL.aub
>>>> clEnqueueNDRangeKernel( bitonicSort ): queue = 1E7117DC, kernel = 009FC164, global_work_size = < 32768 >, local_work_size = < NULL >; EnqueueCounter: 3
<<<< clEnqueueNDRangeKernel created event = 1EBAAE04 -> CL_SUCCESS
AubCapture stopped.

**Comment by jgu222** [comment]
By the way,  it is on DG2.

**Comment by bashbaug** [comment]
Hi @jgu222, please note that this is a public repo.

I just tried aubcapture on my Linux NUC and I'm seeing files dumped as expected.

A few things to try:

1. Add `PrintDebugSettings` to ensure the NEO controls are being picked up properly.
2. On Windows especially, be sure you are using a build that supports aubcapture.
3. Try Linux or a different GPU?

If these work (3 especially) we may need to file an issue against NEO.  Thanks!

**Comment by jgu222** [comment]
I tried it on a different GPU and it works.  Looks like NEO issues.
