### ISSUE TITLE
Hook for `clLinkProgram` options.

### ISSUE THREAD

**Issue by TApplencourt** [intel/opencl-intercept-layer#215]
## Observed Behavior

No option seems to be present to dump the `clLinkProgram` options. Sorry if it's the case and that I didn't find it. 

## Desired Behavior

It will be nice to have a hook to dump the `clLinkProgram` option. Indeed I have a program that hangs at link time. Being able to get the link options without parsing the log will be a big plus.

**Comment by bashbaug** [comment]
Sorry for the slow reply, I just got back from vacation.  This should be easy to add.  Thank you for the report!

**Comment by TApplencourt** [comment]
Thanks! 
No need to excuse, your vacation is far more important than this feature request :)

**Comment by bashbaug** [comment]
I just checked this and it looks like the `clLinkProgram` options can be dumped, but not by default, so you'll need to set the controls to dump something else like the program source, input program binaries, etc:

https://github.com/intel/opencl-intercept-layer/blob/master/intercept/src/intercept.h#L2137

Can you please give this a try and confirm that it works for your use-case?

If so, does it make sense to add a control to dump build options specifically, without necessarily dumping other types of program source?

**Comment by TApplencourt** [comment]
>Can you please give this a try and confirm that it works for your use case?

It kind of works. Meaning I have the `clLinkCompileOption` but it's hard to know which flags come from the build, compile, or link. They are all named like `CLI_0000_B5C0FBCF_0000_FC28ACA8_options.txt`

Log:
```
tapplencourt@foo06:~/tmp> CLI_DumpProgramSPIRV=1 /soft/debuggers/opencl-intercept-layer/build/cliloader/cliloader ./a.out
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
CLIntercept (64-bit) is loading...
CLIntercept file location: /soft/debuggers/opencl-intercept-layer/build/cliloader/../intercept/libOpenCL.so
CLIntercept URL: https://github.com/intel/opencl-intercept-layer
CLIntercept git description: v3.0.2-10-gfe668e9
CLIntercept git refspec: refs/heads/master
CLIntercept git hash: fe668e9b2e98d738c19931fe665a11b7d6ab6367
CLIntercept optional features:
    cliloader(supported)
    cliprof(supported)
    kernel overrides(supported)
    ITT tracing(NOT supported)
    MDAPI(supported)
    clock(steady_clock)
CLIntercept environment variable prefix: CLI_
CLIntercept config file: clintercept.conf
Read OpenCL file name from user parameters: /soft/libraries/khronos/loader/master-2021.06.01/lib64/libOpenCL.so.1
Trying to load dispatch from: /soft/libraries/khronos/loader/master-2021.06.01/lib64/libOpenCL.so.1
Couldn't get exported function pointer to: clGetGLContextInfoKHR
... success!
Control ReportToStderr is set to non-default value: true
Control DumpProgramSPIRV is set to non-default value: true
Timer Started!
... loading complete.
Dumping program options to file (inject): /home/tapplencourt/CLIntercept_Dump/a.out/CLI_0000_B5C0FBCF_0000_FC28ACA8_options.txt
clBuildProgram: Build Success. LOG:

Dumping program options to file (inject): /home/tapplencourt/CLIntercept_Dump/a.out/CLI_0001_B5C0FBCF_0000_FC28ACA8_options.txt
clCompileProgram: Build Success. LOG:

Dumping program options to file (inject): /home/tapplencourt/CLIntercept_Dump/a.out/CLI_0002_00000000_0000_FC28ACA8_options.txt
clLinkProgram: Build Success. LOG:

Total Enqueues: 0

CLIntercept is shutting down...
... shutdown complete.
```

**Comment by bashbaug** [comment]
OK good, that's the behavior I'd expect to see at least.

Would it be helpful to disambiguate the type of options by including a bit more in the filename - `_compile_options.txt`, `_build_options.txt`, `_link_options.txt`?

It is currently possible to determine which are the link options because the "program hash" for the linked program is currently all zeroes, but that may change in the future if I can figure out a meaningful way to hash a linked program.

**Comment by TApplencourt** [comment]
>Would it be helpful to disambiguate the type of options by including a bit more in the filename - _compile_options.txt, _build_options.txt, _link_options.txt?

This will be perfect! 

>It is currently possible to determine which are the link options because the "program hash" for the linked program is currently all zeroes, but that may change in the future if I can figure out a meaningful way to hash a linked program.

Thanks for the hack :). 

Is iterating over all the programs, get their "source/binary/spirV" code via `clGetProgramInfo`, xor it with a hash of all devices ptr and the command-line arguments used to compile and link may work? 
I'm sure I'm missing some subtleties.



I'm sure it's not as simple.

**Comment by bashbaug** [comment]
> > Would it be helpful to disambiguate the type of options by including a bit more in the filename - _compile_options.txt, _build_options.txt, _link_options.txt?
> 
> This will be perfect!

Great, I'll get this added in the next couple of days.



> Is iterating over all the programs [...]

Yeah, I think this would work in that it would generate a unique hash, but without a way to trace back to the program objects that make up the linked program I'm not sure how valuable this would be.

**Comment by bashbaug** [comment]
I think I have this fixed now, see: https://github.com/intel/opencl-intercept-layer/pull/217.  Please take a look - thanks!

**Comment by TApplencourt** [comment]
It worked, thanks a lot! 

A little nitpicking but in documentation of the ENV where you use:
```
>CLI_<Program Number>_<Unique Program Hash Code>_<Compile Count>_<Unique Build Options Hash Code>_options.txt
```
should you add something at the end to clarify that the name of the file now depends on the call made?
```
>CLI_<Program Number>_<Unique Program Hash Code>_<Compile Count>_<Unique Build Options Hash Code>_<ALI_name>_options.txt
```
Can make a PR if you prefer.

**Comment by bashbaug** [comment]
Good idea, fixed (I think) by https://github.com/intel/opencl-intercept-layer/pull/219.
