### ISSUE TITLE
Chrome trace logging produces invalid JSON

### ISSUE THREAD

**Issue by Janonard** [intel/opencl-intercept-layer#367]
## Observed Behavior

When logging the OpenCL calls of an application using the `-ccl` option, I've noticed that the JSON file produced by cliloader is invalid and misses a closing bracket. Also, the last entry in the file has a trailing comma, which would need to be removed to properly close the list of objects. As far as I'm aware, the tracing tool within Chrome accepts this invalid JSON file, but I'm also analyzing the traces with custom scripts and most JSON parsing libraries refuse to parse the trace.

## Desired Behavior

After finishing, the trace file should be valid JSON so that it can be parsed with an arbitrary JSON parsing library.

## Steps to Reproduce

```
mkdir dump
cliloader -ccl --dump-dir dump echo "Hello World"
cat dump/clintercept_trace.json # The printed JSON will be invalid
```

* OpenCL implementation: None, no OpenCL implementation is necessary to reproduce the issue.
* Operating Systems: Verified on NixOS 24.05 and Red Hat Enterprise Linux release 8.8 (Ootpa)

**Comment by bashbaug** [comment]
Thanks!  I'm looking at some options to fix this.

**Comment by bashbaug** [comment]
Can you have a look at #368 and confirm that this generates valid JSON?

**Comment by Janonard** [comment]
Works like a charm, thank you!
