### ISSUE TITLE
Can not trace DeviceTimeLine line to corresponding kernel when KernelInfoTracking is enabled

### ISSUE THREAD

**Issue by shreeniwas-sapre** [intel/opencl-intercept-layer#41]
## Observed Behavior

When DevicePerformanceTimeKernelInfoTracking is enabled along with DevicePerformanceTimelineLogging, the timeline output contains, for example, lines like:
```
>>>> clEnqueueNDRangeKernel( kernel_name ): queue = <qptr>, kernel = <kernptr>, global_work_size = < gws >, local_work_size = < lws >, EnqueueCounter: <enqcounter>

Device Timeline for call <n> to kernel_name  SIMD<x> SPILL=<yy> SLM=<zz> GWS[<gws>] LWS[<lws>] = <t1> ns (queued), <t2> ns (submit), <t3> ns (start), <t4> ns (end)
```
To identify which clEnqueueNDRangeKernel corresponds to the timeline line, one needs to count the calls and find out, the n'th call. This counting is w.r.t. the full key. So the counting should only be within calls to that kernel/gws/lws combination which has the **same** `SIMDxx SPILL=<yy> SLM=<zz> GWS[ <gws> ] LWS[ <lws>]`.

However, when the clEnqueueNDRange is executed, only the kernelname, GWS and LWS are known. So, the corresponding log line also mentions only these three components. It is therefore not easy to identify which calls could possibly match the detailed kernel info. 

## Desired Behavior

The details provided in the device timeline log should be easily traceable to the corresponding API calls. Such details could, for instance, be the absolute API counter. Counting the absolute API counter is unambiguous. 

Ideally, the _tracing_ details should appear not only in the device timeline line, but also in the line describing the clEnqueueNDRange as well, as shown below.

* Also note, that the format of GWS and LWS in the two lines is different as of now. Ideally, GWS/LWS should be reported using a single format anywhere they appear in the log. More generally, any unit of information should appear consistently through out the log. This consistency aspect also relates to [#28](https://github.com/intel/opencl-intercept-layer/issues/28)
* The global_working_size format in the clEnqueueNDRangeKernel line uses ',' to separate the different dimensions. This results in overloading the ',' character since it separates different other elements in the complete line. The 'axb' format avoids using the line-level field separator to separate sub-fields and hence is unambiguous.

```
>>>> clEnqueueNDRangeKernel( kernel_name ): queue = <qptr>, kernel = <kernptr>, GWS[<gws>], LWS = [lws], EnqueueCounter: <enqcounter>, APICounter: <apicounter>


Device Timeline for API counter <m> call <n> to kernel_name  SIMD<x> SPILL=<yy> SLM=<zz> GWS[ <gws> ] LWS[ <lws> ] = <t1> ns (queued), <t2> ns (submit), <t3> ns (start), <t4> ns (end)
```

## Steps to Reproduce

* Enable DevicePerformanceTimeKernelInfoTracking 
* Enable DevicePerformanceTimelineLogging

**Comment by shreeniwas-sapre** [comment]
Changing delimiter from `,` to `x` should work, thanks! Between `GWS` vs `global_work_size`, I do not mind either; but would prefer if the chosen one is used through out.

Enqueue counter is a reasonable substitute for the API counter, so that will work too.  The absolute API counter would provide a unique id for all API calls, and that was why I had suggested it. However, Enqueuecounter is already defined, and would be adequate for the device timeline. 

Logging in the presence of multi-threading scenarios may also require additional changes to the log format, wouldn't it? For instance, right now, different aspects of a call (e.g. the call entry and exit) appear on separate _but consecutive_ lines. These different lines can be put together by virtue of their consecutive nature. Would that be always the case for multi-threaded scenarios? But I think this may already be a point under discussion in [#28](https://github.com/intel/opencl-intercept-layer/issues/28) .

**Comment by bashbaug** [comment]
I believe these issues are all fixed.  Can you please verify and close if so?  Thanks!

**Comment by bashbaug** [comment]
I'm closing this issue since I think everything is fixed.  If it's not, feel free to reopen this issue or add a new one.  Thanks!
