### ISSUE TITLE
System-wide Config File

### ISSUE THREAD

**Issue by bashbaug** [intel/opencl-intercept-layer#72]
## Observed Behavior

The Intercept Layer can currently read from a config file or environment variables, but both of these are per-user controls (the config file is in the user's home directory).  There is currently no way to setup a system-wide config file instead.

## Desired Behavior

Consider adding support for a system-wide config file in addition to the existing per-user controls.  For example, a system-wide config file in `/etc/OpenCL` could be searched if a control is not specified by the existing per-user environment variables or config file.

## Steps to Reproduce

N/A, new feature request.

**Comment by jbrodman** [comment]
This would be great!
