### ISSUE TITLE
Enable ARM/Linux builds

### ISSUE THREAD

**Issue by aaaaajjjryy** [intel/opencl-intercept-layer#8]
## Observed Behavior

Builds fail on ARM/Linux due to binary kernel dependencies

## Desired Behavior

Builds succeed on ARM/Linux

## Steps to Reproduce
Run cmake/make on an ARM/Linux platform

## Patch
Here is the proposed patch:
[arm_linux.txt](https://github.com/intel/opencl-intercept-layer/files/1920861/arm_linux.txt)

**Comment by bashbaug** [comment]
@aaaaajjjryy can you please check if the changes in #9 work for you?  It uses an alternate method to embed the kernel override CL files that should work for both 32-bit and 64-bit Linux builds.  I don't have a setup to test that the 32-bit Linux build functions correctly, but I was able to build successfully on a 32-bit ARM-based Raspberry Pi.

If this doesn't work I'll disable the kernel overrides as you've done in your patch, but I'd like to try this first.  Thanks!

**Comment by aaaaajjjryy** [comment]
@bashbaug : Unfortunately, the version of ld on my setup crashes when converting the kernel:

`> ld -r -b binary Kernels/builtin_kernels.cl -o /home/root/opencl-intercept-layer/bin/CMakeFiles/Kernels/builtin_kernels.o`
`Segmentation fault (core dumped)`
`>ld -v`
`GNU ld (GNU Binutils) 2.27.0.20160806`

**Comment by bashbaug** [comment]
> Unfortunately, the version of ld on my setup crashes when converting the kernel:

OK, that's too bad.

Next possibility: Can I add a CMake variable to include / omit the kernel overrides?  This way configurations that support the kernel overrides can include them, but other configurations can easily omit them.

If this will work, is it OK if the default behavior is to include the kernel overrides?  I suppose I could conditionally set the default based on the configuration, but the `ld` method appears to be working for at least some ARM/Linux configurations.

**Comment by bashbaug** [comment]
I've added the CMake option to include / omit kernel overrides.  Since kernel overrides are included by default, you'll need to explicitly disable them:

    > cmake .. -DENABLE_KERNEL_OVERRIDES=FALSE

If this doesn't work for you, please feel free to reopen this issue.  Thanks!

**Comment by aaaaajjjryy** [comment]
Works as expected, thanks!
